News/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path("", views.NewsList.as_view(), name="home"),
    path('<slug:slug>/', views.NewsDetail.as_view(), name='news_detail'),
    path('<slug:slug>/edit_comment/<int:comment_id>',
         views.comment_edit, name='comment_edit'),
    path('<slug:slug>/delete_comment/<int:comment_id>',
        views.comment_delete, name='comment_delete'),    
    path('like/<slug:slug>', views.NewsLike.as_view(), name='news_like'),
    
]

World_News/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include('News.urls'), name='News_urls'),
    path("accounts/", include("allauth.urls")),
]

News/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField

STATUS = ((0, "Draft"), (1, "Published"))
# Create your models here.
class News(models.Model):
    news_title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    news_author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="news_article"
    )
    news_image = CloudinaryField('image', default='placeholder')
    news_excerpt = models.TextField(blank=True)
    updated_on = models.DateTimeField(auto_now=True)
    news_content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    released_status = models.IntegerField(choices=STATUS, default=0)
    likes = models.ManyToManyField(
        User, related_name='news_like', blank=True)

    class Meta:
        ordering = ["-created_on"]

    def __str__(self):
        return self.news_title

    def number_of_likes(self):
        return self.likes.count()


class Comment(models.Model):
    post = models.ForeignKey(News, on_delete=models.CASCADE,
                             related_name="comments")
    user_name = models.CharField(max_length=80)
    user_email = models.EmailField()
    Comment_content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)

    class Meta:
        ordering = ["created_on"]

    def __str__(self):
        return f"Comment {self.Comment_content} by {self.user_name}"

News/forms.py
from .models import Comment
from django import forms


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('Comment_content',)

        

News/views.py
from django.shortcuts import render, get_object_or_404, reverse
from django.views import generic, View
from django.http import HttpResponseRedirect
from .models import News, Comment
from .forms import CommentForm

# Create your views here.
class NewsList(generic.ListView):
    model = News
    queryset = News.objects.filter(
    released_status=1).order_by("-created_on")
    print('QUERY: ', queryset)
    template_name = "index.html"
    paginate_by = 6


class NewsDetail(View):

    def get(self, request, slug, *args, **kwargs):
        queryset = News.objects.filter(released_status=1)
        post = get_object_or_404(queryset, slug=slug)
        comments = post.comments.filter(approved=True).order_by("-created_on")
        liked = False
        if post.likes.filter(id=self.request.user.id).exists():
            liked = True

        return render(
            request,
            "news_details.html",
            {
                "post": post,
                "comments": comments,
                "commented": False,
                "liked": liked,
                "comment_form": CommentForm()
            },
        )

    def post(self, request, slug, *args, **kwargs):
        queryset = News.objects.filter(released_status=1)
        post = get_object_or_404(queryset, slug=slug)
        comments = post.comments.filter(approved=True).order_by("-created_on")
        liked = False
        if post.likes.filter(id=self.request.user.id).exists():
            liked = True
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            comment_form.instance.email = request.user.email
            comment_form.instance.name = request.user.username
            comment = comment_form.save(commit=False)
            comment.post = post
            comment.save()
        else:
            comment_form = CommentForm()    

        return render(
            request,
            "news_details.html",
            {
                "post": post,
                "comments": comments,
                "commented": True,
                "liked": liked,
                "comment_form": CommentForm()
            },
        )        
class NewsLike(View):
    
    def post(self, request, slug, *args, **kwargs):
        post = get_object_or_404(News, slug=slug)
        if post.likes.filter(id=request.user.id).exists():
            post.likes.remove(request.user)
        else:
            post.likes.add(request.user)

        return HttpResponseRedirect(reverse('news_detail', args=[slug]))

def comment_edit(request, slug, comment_id):
    """
    view to edit comments
    """
    if request.method == "POST":

        queryset = Post.objects.filter(released_status=1)
        post = get_object_or_404(queryset, slug=slug)
        comment = get_object_or_404(Comment, pk=comment_id)
        comment_form = CommentForm(data=request.POST, instance=comment)

        if comment_form.is_valid() and comment.news_author == request.user_name:
            comment = comment_form.save(commit=False)
            comment.post = post
            comment.approved = False
            comment.save()
            messages.add_message(request, messages.SUCCESS, 'Comment Updated!')
        else:
            messages.add_message(request, messages.ERROR, 'Error updating comment!')

    return HttpResponseRedirect(reverse('news_detail', args=[slug]))


def comment_delete(request, slug, comment_id):
    """
    view to delete comment
    """
    queryset = Post.objects.filter(released_status=1)
    post = get_object_or_404(queryset, slug=slug)
    comment = get_object_or_404(Comment, pk=comment_id)

    if comment.author == request.user:
        comment.delete()
        messages.add_message(request, messages.SUCCESS, 'Comment deleted!')
    else:
        messages.add_message(request, messages.ERROR, 'You can only delete your own comments!')

    return HttpResponseRedirect(reverse('news_detail', args=[slug]))    

templates/base.html
<!DOCTYPE html>
<html lang="en" class="h-100">

<head>
  {% load static %}

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="viewport" content="width=device-width">
  <meta name="description" content="WorldNews is source of reliable and valid news from all around the world">
  <meta name="keywords" content="NewsTime, News, World News, Breaking News & Fresh News">

  <!-- CDN - Bootstrap -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">


  <!-- Font Awesome -->
  <script src="https://kit.fontawesome.com/1bc010baf6.js" crossorigin="anonymous"></script>

  <!-- Link to CSS file -->
  <link rel="stylesheet" href="{% static 'css/style.css' %}">

  <!-- Site title -->

  <title>World_News</title>

</head>

<body class="d-flex flex-column h-100">

  <!-- Site NavBar -->
  <nav class="navbar navbar-expand-lg navbar-light bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'home' %}"><span class="brand">W<span class="red-o">o</span>rld<span
            class="thin">|News</span></span></span></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02"
        aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'account_signup' %}">Sign Up</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'account_login' %}">Login</a>
          </li>
          {% endif %}
        </ul>
        <span class="navbar-text text-muted">

          Lima Urzala
        </span>
      </div>
    </div>
  </nav>


  <div class="container-fluid p-0">
    <div class="alert {{ message.tags }} alert-dismissible" id="flash-msg" role="alert">
      <!-- <span aria-hidden="True">&times;</span> -->
      </button>

    </div>
  </div>


  <main class="flex-shrink-0 main-bg">
    {% block content %}
    <!-- Content Goes here -->
    {% endblock content %}
  </main>

  <!-- Footer -->
  <footer class="footer mt-auto py-3 dark-bg">
    <p class="m-0 text-center text-white">Made by Liima Zurmati</p>
    <p class="m-0 text-center text-white">Follow us: <i class="fab fa-facebook-square ms-3"></i>
      <i class="fab fa-twitter-square ms-3"></i>
      <i class="fab fa-instagram-square ms-3"></i>
      <i class="fab fa-youtube-square ms-3"></i></p>
  </footer>
  <!-- Link to Javascript File  -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous">
  </script>
  {% block extras %}
  {% endblock %}
</body>

</html>

templates/index.html
{% extends "base.html" %}

{% block content %}

<div class="container-fluid">
    <div class="row">
        <!-- Blog Entries Column -->
        <div class="col-12 mt-3 left">
            <div class="row">
                <!-- Card's code from Bootstrap  -->
                {% for news in news_list %}
                <div class="col-md-4">
                    <div class="card mb-4">
                        <div class="card-body">
                            <div class="image-container">
                                {% if "placeholder" in news.news_image.url %}
                                <img class="card-img-top"
                                    src="https://codeinstitute.s3.amazonaws.com/fullstack/blog/default.jpg">
                                {% else %}
                                <img class="card-img-top" src=" {{ news.news_excerpt.url }}">
                                {% endif %}
                                <div class="image-flash">
                                    <p class="author">Author: {{ news.news_author }}</p>
                                </div>
                            </div>
                            <a href="{% url 'news_detail' news.slug  %}" class="post-link">
                                <h2 class="card-title">{{ news.news_title }}</h2>
                                <p class="card-text">{{ news.news_excerpt }}</p>
                            </a>
                            <hr />
                            <p class="card-text text-muted h6">{{ news.created_on}} <i class="far fa-heart"></i>
                                {{ news.number_of_likes }}</p>
                        </div>
                    </div>
                </div>
                {% if forloop.counter|divisibleby:3 %}
            </div>
            <div class="row">
                {% endif %}
                {% endfor %}

            </div>
        </div>
    </div>
    {% if is_paginated %}
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; Previous </a></li>
            {% endif %}
            {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>

            {% endif %}
        </ul>
    </nav>
    {% endif %}
</div>
{%endblock%}

templates/mfa/authenticate.html
{% extends "mfa/base_entrance.html" %}
{% load i18n %}
{% load allauth %}
{% block head_title %}
    {% trans "Sign In" %}
{% endblock head_title %}
{% block content %}
    {% element h1 %}
        {% trans "Two-Factor Authentication" %}
    {% endelement %}
    <p>
        {% blocktranslate %}Your account is protected by two-factor authentication. Please enter an authenticator code:{% endblocktranslate %}
    </p>
    {% url 'mfa_authenticate' as action_url %}
    {% element form form=form method="post" action=action_url %}
        {% slot body %}
            {% csrf_token %}
            {% element fields form=form unlabeled=True %}
            {% endelement %}
        {% endslot %}
        {% slot actions %}
            {% element button type="submit" tags="primary,mfa,login" %}
                {% trans "Sign In" %}
            {% endelement %}
            {% url "account_login" as login_url %}
            {% element button href=login_url tags="link,secondary,mfa,cancel" %}
                {% trans "Cancel" %}
            {% endelement %}
        {% endslot %}
    {% endelement %}
{% endblock content %}

templates/mfa/base_entrance.html
{% extends "allauth/layouts/entrance.html" %}

templates/mfa/base_manage.html
{% extends "allauth/layouts/manage.html" %}

templates/mfa/index.html
{% extends "mfa/base_manage.html" %}
{% load allauth %}
{% load i18n %}
{% block head_title %}
    {% trans "Two-Factor Authentication" %}
{% endblock head_title %}
{% block content %}
    {% element h1 tags="mfa,index" %}
        {% trans "Two-Factor Authentication" %}
    {% endelement %}
    {% if "totp" in MFA_SUPPORTED_TYPES %}
        {% element panel %}
            {% slot title %}
                {% translate "Authenticator App" %}
            {% endslot %}
            {% slot body %}
                {% if authenticators.totp %}
                    <p>{% translate "Authentication using an authenticator app is active." %}</p>
                {% else %}
                    <p>{% translate "An authenticator app is not active." %}</p>
                {% endif %}
            {% endslot %}
            {% slot actions %}
                {% url 'mfa_deactivate_totp' as deactivate_url %}
                {% url 'mfa_activate_totp' as activate_url %}
                {% if authenticators.totp %}
                    {% element button href=deactivate_url tags="danger,delete,panel" %}
                        {% translate "Deactivate" %}
                    {% endelement %}
                {% else %}
                    {% element button href=activate_url tags="panel" %}
                        {% translate "Activate" %}
                    {% endelement %}
                {% endif %}
            {% endslot %}
        {% endelement %}
    {% endif %}
    {% if "recovery_codes" in MFA_SUPPORTED_TYPES %}
        {% with total_count=authenticators.recovery_codes.generate_codes|length unused_count=authenticators.recovery_codes.get_unused_codes|length %}
            {% element panel %}
                {% slot title %}
                    {% translate "Recovery Codes" %}
                {% endslot %}
                {% slot body %}
                    {% if authenticators.recovery_codes %}
                        <p>
                            {% blocktranslate count unused_count=unused_count %}There is {{ unused_count }} out of {{ total_count }} recovery codes available.{% plural %}There are {{ unused_count }} out of {{ total_count }} recovery codes available.{% endblocktranslate %}
                        </p>
                    {% else %}
                        <p>{% translate "No recovery codes set up." %}</p>
                    {% endif %}
                {% endslot %}
                {% if is_mfa_enabled %}
                    {% if authenticators.recovery_codes %}
                        {% if unused_count > 0 %}
                            {% slot actions %}
                                {% url 'mfa_view_recovery_codes' as view_url %}
                                {% element button href=view_url tags="panel" %}
                                    {% translate "View" %}
                                {% endelement %}
                            {% endslot %}
                            {% slot actions %}
                                {% url 'mfa_download_recovery_codes' as download_url %}
                                {% element button href=download_url tags="secondary,panel" %}
                                    {% translate "Download" %}
                                {% endelement %}
                            {% endslot %}
                        {% endif %}
                    {% endif %}
                    {% slot actions %}
                        {% url 'mfa_generate_recovery_codes' as generate_url %}
                        {% element button href=generate_url tags="secondary,panel" %}
                            {% translate "Generate" %}
                        {% endelement %}
                    {% endslot %}
                {% endif %}
            {% endelement %}
        {% endwith %}
    {% endif %}
{% endblock content %}

templates/mfa/reauthenticate.html
{% extends "account/base_reauthenticate.html" %}
{% load i18n %}
{% load allauth %}
{% block reauthenticate_content %}
    <p>{% blocktranslate %}Enter an authenticator code:{% endblocktranslate %}</p>
    {% url 'mfa_reauthenticate' as action_url %}
    {% element form form=form method="post" action=action_url %}
        {% slot body %}
            {% csrf_token %}
            {% element fields form=form unlabeled=True %}
            {% endelement %}
            {{ redirect_field }}
        {% endslot %}
        {% slot actions %}
            {% element button type="submit" tags="primary,mfa,login" %}
                {% trans "Confirm" %}
            {% endelement %}
        {% endslot %}
    {% endelement %}
{% endblock %}

templates/mfa/recovery_codes/base.html
{% extends "mfa/base_manage.html" %}
{% load i18n %}
{% block head_title %}
    {% trans "Recovery Codes" %}
{% endblock head_title %}

templates/mfa/recovery_codes/generate.html
{% extends "mfa/recovery_codes/base.html" %}
{% load i18n %}
{% load allauth %}
{% block content %}
    {% element h1 %}
        {% translate "Recovery Codes" %}
    {% endelement %}
    <p>
        {% blocktranslate %}You are about to generate a new set of recovery codes for your account.{% endblocktranslate %}
        {% if unused_code_count %}
            {% blocktranslate %}This action will invalidate your existing codes.{% endblocktranslate %}
        {% endif %}
        {% blocktranslate %}Are you sure?{% endblocktranslate %}
    </p>
    {% url 'mfa_generate_recovery_codes' as action_url %}
    {% element form method="post" action=action_url no_visible_fields=True %}
        {% slot body %}
            {% csrf_token %}
            {{ form.as_p }}
        {% endslot %}
        {% slot actions %}
            {% setvar tags %}
                {% if unused_code_count %}
                    danger
                {% else %}
                {% endif %}
            {% endsetvar %}
            {% element button type="submit" tags=tags %}
                {% trans "Generate" %}
            {% endelement %}
        {% endslot %}
    {% endelement %}
{% endblock content %}

templates/mfa/recovery_codes/index.html
{% extends "mfa/recovery_codes/base.html" %}
{% load i18n %}
{% load allauth %}
{% block content %}
    {% element h1 %}
        {% translate "Recovery Codes" %}
    {% endelement %}
    <p>
        {% blocktranslate count unused_count=unused_codes|length %}There is {{ unused_count }} out of {{ total_count }} recovery codes available.{% plural %}There are {{ unused_count }} out of {{ total_count }} recovery codes available.{% endblocktranslate %}
    </p>
    {% element field id="recovery_codes" type="textarea" disabled=True rows=unused_codes|length readonly=True %}
        {% slot label %}
            {% translate "Unused codes" %}
        {% endslot %}
        {% comment %} djlint:off {% endcomment %}
    {% slot value %}{% for code in unused_codes %}{% if forloop.counter0 %}
{% endif %}{{ code }}{% endfor %}{% endslot %}
{% comment %} djlint:on {% endcomment %}
{% endelement %}
{% if unused_codes %}
{% url 'mfa_download_recovery_codes' as download_url %}
{% element button href=download_url %}
{% translate "Download codes" %}
{% endelement %}
{% endif %}
{% url 'mfa_generate_recovery_codes' as generate_url %}
{% element button href=generate_url %}
{% translate "Generate new codes" %}
{% endelement %}
{% endblock content %}

templates/mfa/totp/activate_form.html
{% extends "mfa/totp/base.html" %}
{% load allauth i18n %}
{% block head_title %}
    {% translate "Activate Authenticator App" %}
{% endblock head_title %}
{% block content %}
    {% element h1 %}
        {% translate "Activate Authenticator App" %}
    {% endelement %}
    <p>
        {% blocktranslate %}To protect your account with two-factor authentication, scan the QR code below with your authenticator app. Then, input the verification code generated by the app below.{% endblocktranslate %}
    </p>
    {% url 'mfa_activate_totp' as action_url %}
    {% element form form=form method="post" action=action_url %}
        {% slot body %}
            {% element img src=totp_svg_data_uri alt=form.secret tags="mfa,totp,qr" %}
            {% endelement %}
            {% csrf_token %}
            {% element field id="authenticator_secret" type="text" value=form.secret disabled=True %}
                {% slot label %}
                    {% translate "Authenticator secret" %}
                {% endslot %}
                {% slot help_text %}
                    {% translate "You can store this secret and use it to reinstall your authenticator app at a later time." %}
                {% endslot %}
            {% endelement %}
            {% element fields form=form %}
            {% endelement %}
        {% endslot %}
        {% slot actions %}
            {% element button type="submit" %}
                {% trans "Activate" %}
            {% endelement %}
        {% endslot %}
    {% endelement %}
{% endblock content %}

templates/mfa/totp/base.html
{% extends "mfa/base_manage.html" %}
{% load i18n %}
{% block head_title %}
    {% trans "Authenticator App" %}
{% endblock head_title %}

templates/mfa/totp/deactivate_form.html
{% extends "mfa/totp/base.html" %}
{% load i18n %}
{% load allauth %}
{% block head_title %}
    {% trans "Deactivate Authenticator App" %}
{% endblock head_title %}
{% block content %}
    {% element h1 %}
        {% trans "Deactivate Authenticator App" %}
    {% endelement %}
    <p>
        {% blocktranslate %}You are about to deactivate authenticator app based authentication. Are you sure?{% endblocktranslate %}
    </p>
    {% url 'mfa_deactivate_totp' as action_url %}
    {% element form form=form method="post" action=action_url no_visible_fields=True %}
        {% slot body %}
            {% csrf_token %}
            {% element fields form=form %}
                {{ form.as_p }}
            {% endelement %}
        {% endslot %}
        {% slot actions %}
            {% element button tags="danger,delete" type="submit" %}
                {% trans "Deactivate" %}
            {% endelement %}
        {% endslot %}
    {% endelement %}
{% endblock content %}

templates/news_details.html
{% extends 'base.html' %} {% block content %}
{% load crispy_forms_tags %}
{% load static %}

<div class="masthead">
    <div class="container">
        <div class="row g-0">
            <div class="col-md-6 masthead-text">
                <!-- News title and details -->
                <h1 class="post-title">{{ post.news_title }}</h1>
               
                <p class="post-subtitle">{{ post.news_author }} | {{ post.created_on }}</p>
            </div>
            <div class="d-none d-md-block col-md-6 masthead-image">
                
                {% if "placeholder" in post.news_image.url %}
                <img src="{% static 'image/kabul.jpg' %}" width="100%">
                {% else %}
                <img src=" {{ post.news_image.url }}" width="100%">
                {% endif %}
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col card mb-4  mt-3 left  top">
            <div class="card-body">
<!-- News Content -->
                <p class="card-text ">
                    {{ post.news_content | safe }}
                </p>

                 <!-- Likes and comments -->
                 <div class="row">

                    <div class="col-1">
                        <strong>
                            {% if user.is_authenticated %}
                            <form class="d-inline" action="{% url 'news_like' post.slug %}" method="POST">
                                {% csrf_token %}
                                {% if liked %}
                                <button type="submit" name="blogpost_id" value="{{post.slug}}" class="btn-like"><i class="fas fa-heart"></i></button>
                                {% else %}
                                <button type="submit" name="blogpost_id" value="{{post.slug}}" class="btn-like"><i class="far fa-heart"></i></button>
                                {% endif %}
                            </form>
                            {% else %}
                            <span class="text-secondary"><i class="far fa-heart"></i></span>
                            {% endif %}
                        <!-- The number of likes goes before the closing strong tag -->
                        <span class="text-secondary">{{ post.number_of_likes }} </span>
                        </strong>
                    </div>
                    <div class="col-1">
                        {% with comments.count as total_comments %}
                        <strong class="text-secondary"><i class="far fa-comments"></i>
                            <!-- Our total_comments variable goes before the closing strong tag -->
                            {{ total_comments }}</strong>
                        {% endwith %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <hr>
        </div>
    </div>

           <!-- Comments -->
    <div class="row">
        <div class="col-md-8 card mb-4  mt-3 ">
            <h3>Comments:</h3>
            <div class="card-body">
              
                {% for comment in comments %}
                <div class="comments" style="padding: 10px;">
                    <p class="font-weight-bold">
                       
                        {{ comment.user_name }}
                        <span class=" text-muted font-weight-normal">
                          
                            {{ comment.created_on }}
                        </span> wrote:
                    </p>
                    
                    {{ comment.Comment_content | linebreaks }}
                </div>
               
                {% endfor %}
            </div>
        </div>

        <div class="col-md-4 card mb-4  mt-3 ">
            <div class="card-body">

            
            {% if commented %}
            <div class="alert alert-success" role="alert">
                Your comment is awaiting approval
                <button class="btn btn-delete"
                comment_id="{{ comment.id }}">Delete</button>
                <button class="btn btn-edit"
                comment_id="{{ comment.id }}">Edit</button>
            </div>

            {% else %}
            {% if user.is_authenticated %}

            <h3>Leave a comment:</h3>
            <p>Posting as: {{ user.user_name }}</p>
            <form method="post" style="margin-top: 1.3em;">
                {{ comment_form | crispy }}
                {% csrf_token %}
                <button type="submit" class="btn btn-signup btn-lg">Submit</button>
            </form>
            {% endif %}
            {% endif %}
        </div>
    </div>
</div>
</div>
<!-- Delete confirmation modal -->
<div class="modal fade" id="deleteModal" tabindex="-1"
  aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title"
          id="deleteModalLabel">Delete comment?</h5>
        <button type="button" class="btn-close"
          data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Are you sure you want to delete your comment?
        This action cannot be undo.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary"
          data-bs-dismiss="modal">Close</button>
        <a id="deleteConfirm" href="#" class="btn
          btn-danger">Delete</a>
      </div>
    </div>
  </div>
</div>


{% endblock content %}
{% block extras %}
<script src="{% static 'js/comments.js' %}"></script>
{% endblock %}

templates/usersessions/base_manage.html
{% extends "allauth/layouts/manage.html" %}